# For development

services:
  server:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - abeille-data:/db
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .mypy_cache
            - .vscode
volumes:
  abeille-data:
