name: Docker Image CI

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6.9.0
      with:
        push: true
        tags: actionbrk/abeille:latest
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
